/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppAccountRouteImport } from './routes/_app/_account'
import { Route as AppHomeRouteImport } from './routes/_app/_home'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AppAccountApiKeysRouteImport } from './routes/_app/_account/api-keys'
import { Route as AppAccountNotificationsRouteImport } from './routes/_app/_account/notifications'
import { Route as AppAccountProfileRouteImport } from './routes/_app/_account/profile'
import { Route as AppAccountTeamsRouteImport } from './routes/_app/_account/teams'
import { Route as AppHomeAnalyseRouteImport } from './routes/_app/_home/analyse'
import { Route as AppHomeComplianceRouteImport } from './routes/_app/_home/compliance'
import { Route as AppHomeDashboardRouteImport } from './routes/_app/_home/dashboard'
import { Route as AppHomeHistoryRouteImport } from './routes/_app/_home/history'
import { Route as AppHomeRiskScoreRouteImport } from './routes/_app/_home/risk-score'
import { Route as AppHomeCodemapAnalysisIdRouteImport } from './routes/_app/_home/codemap.$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AppAccountApiKeysRoute = AppAccountApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountTeamsRoute = AppAccountTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppHomeAnalyseRoute = AppHomeAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => AppHomeRoute,
} as any)
const AppHomeComplianceRoute = AppHomeComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppHomeRoute,
} as any)
const AppHomeDashboardRoute = AppHomeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppHomeRoute,
} as any)
const AppHomeHistoryRoute = AppHomeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppHomeRoute,
} as any)
const AppHomeRiskScoreRoute = AppHomeRiskScoreRouteImport.update({
  id: '/risk-score',
  path: '/risk-score',
  getParentRoute: () => AppHomeRoute,
} as any)
const AppHomeCodemapAnalysisIdRoute =
  AppHomeCodemapAnalysisIdRouteImport.update({
    id: '/codemap/$analysisId',
    path: '/codemap/$analysisId',
    getParentRoute: () => AppHomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/api-keys': typeof AppAccountApiKeysRoute
  '/notifications': typeof AppAccountNotificationsRoute
  '/profile': typeof AppAccountProfileRoute
  '/teams': typeof AppAccountTeamsRoute
  '/analyse': typeof AppHomeAnalyseRoute
  '/compliance': typeof AppHomeComplianceRoute
  '/dashboard': typeof AppHomeDashboardRoute
  '/history': typeof AppHomeHistoryRoute
  '/risk-score': typeof AppHomeRiskScoreRoute
  '/codemap/$analysisId': typeof AppHomeCodemapAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/api-keys': typeof AppAccountApiKeysRoute
  '/notifications': typeof AppAccountNotificationsRoute
  '/profile': typeof AppAccountProfileRoute
  '/teams': typeof AppAccountTeamsRoute
  '/analyse': typeof AppHomeAnalyseRoute
  '/compliance': typeof AppHomeComplianceRoute
  '/dashboard': typeof AppHomeDashboardRoute
  '/history': typeof AppHomeHistoryRoute
  '/risk-score': typeof AppHomeRiskScoreRoute
  '/codemap/$analysisId': typeof AppHomeCodemapAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/_account': typeof AppAccountRouteWithChildren
  '/_app/_home': typeof AppHomeRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/_account/api-keys': typeof AppAccountApiKeysRoute
  '/_app/_account/notifications': typeof AppAccountNotificationsRoute
  '/_app/_account/profile': typeof AppAccountProfileRoute
  '/_app/_account/teams': typeof AppAccountTeamsRoute
  '/_app/_home/analyse': typeof AppHomeAnalyseRoute
  '/_app/_home/compliance': typeof AppHomeComplianceRoute
  '/_app/_home/dashboard': typeof AppHomeDashboardRoute
  '/_app/_home/history': typeof AppHomeHistoryRoute
  '/_app/_home/risk-score': typeof AppHomeRiskScoreRoute
  '/_app/_home/codemap/$analysisId': typeof AppHomeCodemapAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-keys'
    | '/notifications'
    | '/profile'
    | '/teams'
    | '/analyse'
    | '/compliance'
    | '/dashboard'
    | '/history'
    | '/risk-score'
    | '/codemap/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api-keys'
    | '/notifications'
    | '/profile'
    | '/teams'
    | '/analyse'
    | '/compliance'
    | '/dashboard'
    | '/history'
    | '/risk-score'
    | '/codemap/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/pricing'
    | '/_app/_account'
    | '/_app/_home'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_app/_account/api-keys'
    | '/_app/_account/notifications'
    | '/_app/_account/profile'
    | '/_app/_account/teams'
    | '/_app/_home/analyse'
    | '/_app/_home/compliance'
    | '/_app/_home/dashboard'
    | '/_app/_home/history'
    | '/_app/_home/risk-score'
    | '/_app/_home/codemap/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_account': {
      id: '/_app/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_home': {
      id: '/_app/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/_account/api-keys': {
      id: '/_app/_account/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppAccountApiKeysRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/_account/notifications': {
      id: '/_app/_account/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppAccountNotificationsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/_account/profile': {
      id: '/_app/_account/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/_account/teams': {
      id: '/_app/_account/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppAccountTeamsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/_home/analyse': {
      id: '/_app/_home/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AppHomeAnalyseRouteImport
      parentRoute: typeof AppHomeRoute
    }
    '/_app/_home/compliance': {
      id: '/_app/_home/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppHomeComplianceRouteImport
      parentRoute: typeof AppHomeRoute
    }
    '/_app/_home/dashboard': {
      id: '/_app/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppHomeDashboardRouteImport
      parentRoute: typeof AppHomeRoute
    }
    '/_app/_home/history': {
      id: '/_app/_home/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHomeHistoryRouteImport
      parentRoute: typeof AppHomeRoute
    }
    '/_app/_home/risk-score': {
      id: '/_app/_home/risk-score'
      path: '/risk-score'
      fullPath: '/risk-score'
      preLoaderRoute: typeof AppHomeRiskScoreRouteImport
      parentRoute: typeof AppHomeRoute
    }
    '/_app/_home/codemap/$analysisId': {
      id: '/_app/_home/codemap/$analysisId'
      path: '/codemap/$analysisId'
      fullPath: '/codemap/$analysisId'
      preLoaderRoute: typeof AppHomeCodemapAnalysisIdRouteImport
      parentRoute: typeof AppHomeRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountApiKeysRoute: typeof AppAccountApiKeysRoute
  AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountTeamsRoute: typeof AppAccountTeamsRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountApiKeysRoute: AppAccountApiKeysRoute,
  AppAccountNotificationsRoute: AppAccountNotificationsRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountTeamsRoute: AppAccountTeamsRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppHomeRouteChildren {
  AppHomeAnalyseRoute: typeof AppHomeAnalyseRoute
  AppHomeComplianceRoute: typeof AppHomeComplianceRoute
  AppHomeDashboardRoute: typeof AppHomeDashboardRoute
  AppHomeHistoryRoute: typeof AppHomeHistoryRoute
  AppHomeRiskScoreRoute: typeof AppHomeRiskScoreRoute
  AppHomeCodemapAnalysisIdRoute: typeof AppHomeCodemapAnalysisIdRoute
}

const AppHomeRouteChildren: AppHomeRouteChildren = {
  AppHomeAnalyseRoute: AppHomeAnalyseRoute,
  AppHomeComplianceRoute: AppHomeComplianceRoute,
  AppHomeDashboardRoute: AppHomeDashboardRoute,
  AppHomeHistoryRoute: AppHomeHistoryRoute,
  AppHomeRiskScoreRoute: AppHomeRiskScoreRoute,
  AppHomeCodemapAnalysisIdRoute: AppHomeCodemapAnalysisIdRoute,
}

const AppHomeRouteWithChildren =
  AppHomeRoute._addFileChildren(AppHomeRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppHomeRoute: typeof AppHomeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppHomeRoute: AppHomeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
